### ISSUE TITLE
OpenCV Error: Unsupported Format

### ISSUE THREAD

**Issue by momo-the-monster** [alvarohub/Example_CameraProjectorCalibration#1]
I get the following error after a successful build of the project:

---

OpenCV Error: Unsupported format or combination of formats (Input parameters must be a matrices!) in cvCalibrationMatrixValues, file /Users/theo/Downloads/OpenCV-2.3.1/modules/calib3d/src/calibration.cpp, line 1777
terminate called after throwing an instance of 'cv::Exception'
## what():  /Users/theo/Downloads/OpenCV-2.3.1/modules/calib3d/src/calibration.cpp:1777: error: (-210) Input parameters must be a matrices! in function cvCalibrationMatrixValues

It looks like the setup() method in testApp.cpp tries to load .yml files that don't exist - settingsPatternCamera.yml and settingsProjectionPatternPixels.yml. Could this be related?

**Comment by alvarohub** [comment]
Hi there, 
That's right, the files where missing. Some problem with a rogue .gitignore file... I have added them now. 
Sorry

ps: Print the chessboard_8x5.pdf and glue it to a larger white board as in the video (note the orientation of the pattern, if you glue it the other way, the dynamically projected pattern will be outside the board).

**Comment by momo-the-monster** [comment]
Thanks so much - no need to apologize, I appreciate your work on this and it's very kind of you to share your work and respond to these messages.
